[build]
  publish = "."
  command = "echo 'Static deploy - no build step'"

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/submit"
  to = "/submit.html"
  status = 200

[[redirects]]
  from = "/config"
  to = "/config.json"
  status = 200

